#constants.py

industry={}
industry["Agricultural Chemicals"]=112
industry["Aluminum"]=132
industry["Chemicals - Major Diversified"]=110
industry["Copper"]=131
industry["Gold"]=134
industry["Independent Oil & Gas"]=121
industry["Industrial Metals & Minerals"]=133
industry["Major Integrated Oil & Gas"]=120
industry["Nonmetallic Mineral Mining"]=136
industry["Oil & Gas Drilling & Exploration"]=123
industry["Oil & Gas Equipment & Services"]=124
industry["Oil & Gas Pipelines"]=125
industry["Oil & Gas Refining & Marketing"]=122
industry["Silver"]=135
industry["Specialty Chemicals"]=113
industry["Steel & Iron"]=130
industry["Synthetics"]=111
industry["Appliances"]=310
industry["Auto Manufacturers - Major"]=330
industry["Auto Parts"]=333
industry["Beverages - Brewers"]=346
industry["Beverages - Soft Drinks"]=348
industry["Beverages - Wineries & Distillers"]=347
industry["Business Equipment"]=313
industry["Cigarettes"]=350
industry["Cleaning Products"]=326
industry["Confectioners"]=345
industry["Dairy Products"]=344
industry["Electronic Equipment"]=314
industry["Farm Products"]=341
industry["Food - Major Diversified"]=340
industry["Home Furnishings & Fixtures"]=311
industry["Housewares & Accessories"]=312
industry["Meat Products"]=343
industry["Office Supplies"]=327
industry["Packaging & Containers"]=325
industry["Paper & Paper Products"]=324
industry["Personal Products"]=323
industry["Photographic Equipment & Supplies"]=318
industry["Processed & Packaged Goods"]=342
industry["Recreational Goods, Other"]=317
industry["Recreational Vehicles"]=332
industry["Rubber & Plastics"]=322
industry["Sporting Goods"]=316
industry["Textile - Apparel Clothing"]=320
industry["Textile - Apparel Footwear & Accessories"]=321
industry["Tobacco Products, Other"]=351
industry["Toys & Games"]=315
industry["Trucks & Other Vehicles"]=331
industry["Accident & Health Insurance"]=431
industry["Asset Management"]=422
industry["Closed-End Fund - Debt"]=425
industry["Closed-End Fund - Equity"]=426
industry["Closed-End Fund - Foreign"]=427
industry["Credit Services"]=424
industry["Diversified Investments"]=423
industry["Foreign Money Center Banks"]=417
industry["Foreign Regional Banks"]=418
industry["Insurance Brokers"]=434
industry["Investment Brokerage - National"]=420
industry["Investment Brokerage - Regional"]=421
industry["Life Insurance"]=430
industry["Money Center Banks"]=410
industry["Mortgage Investment"]=447
industry["Property & Casualty Insurance"]=432
industry["Property Management"]=448
industry["REIT - Diversified"]=440
industry["REIT - Healthcare Facilities"]=442
industry["REIT - Hotel/Motel"]=443
industry["REIT - Industrial"]=444
industry["REIT - Office"]=441
industry["REIT - Residential"]=445
industry["REIT - Retail"]=446
industry["Real Estate Development"]=449
industry["Regional - Mid-Atlantic Banks"]=412
industry["Regional - Midwest Banks"]=414
industry["Regional - Northeast Banks"]=411
industry["Regional - Pacific Banks"]=416
industry["Regional - Southeast Banks"]=413
industry["Regional - Southwest Banks"]=415
industry["Savings & Loans"]=419
industry["Surety & Title Insurance"]=433
industry["Biotechnology"]=515
industry["Diagnostic Substances"]=516
industry["Drug Delivery"]=513
industry["Drug Manufacturers - Major"]=510
industry["Drug Manufacturers - Other"]=511
industry["Drug Related Products"]=514
industry["Drugs - Generic"]=512
industry["Health Care Plans"]=522
industry["Home Health Care"]=526
industry["Hospitals"]=524
industry["Long-Term Care Facilities"]=523
industry["Medical Appliances & Equipment"]=521
industry["Medical Instruments & Supplies"]=520
industry["Medical Laboratories & Research"]=525
industry["Medical Practitioners"]=527
industry["Specialized Health Services"]=528
industry["Aerospace/Defense - Major Diversified"]=610
industry["Aerospace/Defense Products & Services"]=611
industry["Cement"]=633
industry["Diversified Machinery"]=622
industry["Farm & Construction Machinery"]=620
industry["General Building Materials"]=634
industry["General Contractors"]=636
industry["Heavy Construction"]=635
industry["Industrial Electrical Equipment"]=627
industry["Industrial Equipment & Components"]=621
industry["Lumber, Wood Production"]=632
industry["Machine Tools & Accessories"]=624
industry["Manufactured Housing"]=631
industry["Metal Fabrication"]=626
industry["Pollution & Treatment Controls"]=623
industry["Residential Construction"]=630
industry["Small Tools & Accessories"]=625
industry["Textile Industrial"]=628
industry["Waste Management"]=637
industry["Advertising Agencies"]=720
industry["Air Delivery & Freight Services"]=773
industry["Air Services, Other"]=772
industry["Apparel Stores"]=730
industry["Auto Dealerships"]=744
industry["Auto Parts Stores"]=738
industry["Auto Parts Wholesale"]=750
industry["Basic Materials Wholesale"]=758
industry["Broadcasting - Radio"]=724
industry["Broadcasting - TV"]=723
industry["Building Materials Wholesale"]=751
industry["Business Services"]=760
industry["CATV Systems"]=725
industry["Catalog & Mail Order Houses"]=739
industry["Computers Wholesale"]=755
industry["Consumer Services"]=763
industry["Department Stores"]=731
industry["Discount, Variety Stores"]=732
industry["Drug Stores"]=733
industry["Drugs Wholesale"]=756
industry["Education & Training Services"]=766
industry["Electronics Stores"]=735
industry["Electronics Wholesale"]=753
industry["Entertainment - Diversified"]=722
industry["Food Wholesale"]=757
industry["Gaming Activities"]=714
industry["General Entertainment"]=716
industry["Grocery Stores"]=734
industry["Home Furnishing Stores"]=737
industry["Home Improvement Stores"]=736
industry["Industrial Equipment Wholesale"]=752
industry["Jewelry Stores"]=742
industry["Lodging"]=710
industry["Major Airlines"]=770
industry["Management Services"]=769
industry["Marketing Services"]=721
industry["Medical Equipment Wholesale"]=754
industry["Movie Production, Theaters"]=726
industry["Music & Video Stores"]=743
industry["Personal Services"]=762
industry["Publishing - Books"]=729
industry["Publishing - Newspapers"]=727
industry["Publishing - Periodicals"]=728
industry["Railroads"]=776
industry["Regional Airlines"]=771
industry["Rental & Leasing Services"]=761
industry["Research Services"]=768
industry["Resorts & Casinos"]=711
industry["Restaurants"]=712
industry["Security & Protection Services"]=765
industry["Shipping"]=775
industry["Specialty Eateries"]=713
industry["Specialty Retail, Other"]=745
industry["Sporting Activities"]=715
industry["Sporting Goods Stores"]=740
industry["Staffing & Outsourcing Services"]=764
industry["Technical Services"]=767
industry["Toy & Hobby Stores"]=741
industry["Trucking"]=774
industry["Wholesale, Other"]=759
industry["Application Software"]=821
industry["Business Software & Services"]=826
industry["Communication Equipment"]=841
industry["Computer Based Systems"]=812
industry["Computer Peripherals"]=815
industry["Data Storage Devices"]=813
industry["Diversified Communication Services"]=846
industry["Diversified Computer Systems"]=810
industry["Diversified Electronics"]=836
industry["Healthcare Information Services"]=825
industry["Information & Delivery Services"]=827
industry["Information Technology Services"]=824
industry["Internet Information Providers"]=851
industry["Internet Service Providers"]=850
industry["Internet Software & Services"]=852
industry["Long Distance Carriers"]=843
industry["Multimedia & Graphics Software"]=820
industry["Networking & Communication Devices"]=814
industry["Personal Computers"]=811
industry["Printed Circuit Boards"]=835
industry["Processing Systems & Products"]=842
industry["Scientific & Technical Instruments"]=837
industry["Security Software & Services"]=823
industry["Semiconductor - Broad Line"]=830
industry["Semiconductor - Integrated Circuits"]=833
industry["Semiconductor - Specialized"]=832
industry["Semiconductor Equipment & Materials"]=834
industry["Semiconductor- Memory Chips"]=831
industry["Technical & System Software"]=822
industry["Telecom Services - Domestic"]=844
industry["Telecom Services - Foreign"]=845
industry["Wireless Communications"]=840
industry["Diversified Utilities"]=913
industry["Electric Utilities"]=911
industry["Foreign Utilities"]=910
industry["Gas Utilities"]=912
industry["Water Utilities"]=914
